#
##
### 1 BASIC DANCER CONFIG
##
#

#appname: a Dancer config value
appname: "Salsa_OAI"

#content_type: This is default content type for dancer. Salsa_OAI sets text/xml
# where appropriate
content_type: "text/html"

#
##
### 2 TRANSFORMATIONS
##
#

#XSLT_dir (path):
# dir where mappings are located (transforming native format to target format)
XSLT_dir: '/home/Mengel/projects/Salsa_OAI2/xslt'

#xslt (path):
# beautify stylesheet, path relative to public dir in Dancer
xslt: '/oai2.xsl'

nativePrefix: 'mpx'
native_ns_uri: 'http://www.mpx.org/mpx'
#schemaLocation for validating native format (used in digest.pl)
nativeSchema: '/home/Mengel/projects/MPX/latest/mpx.xsd'

#
##
### 3 MAPPING / CALLBACKS
##
#

#extractRecords (callback): returns HTTP::OAI::Record from source xml
extractRecords: 'Salsa_OAI::MPX::extractRecords'

#locateXSL (callback): finds xsl for mapping on disk
locateXSL: 'Salsa_OAI::MPX::locateXSL'

#setLibrary (callback): dont remember what this does
setLibraryCB: 'Salsa_OAI::salsa_setLibrary'

#TODO: message callback
debug: 'Salsa_OAI::salsa_debug'
warning: 'Salsa_OAI::salsa_debug'

#
##
### 4 OAI IDENTIFY FOR THIS SERVER
##
#

#adminEmail: for Identify (required)
adminEmail: "mauricemengel@gmail.com"

#baseURL (url): for Identify verb (required)
# also used to overwrite real requestURL
baseURL: "http://localhost:3000/oai"

#deletedRecord: does repository support deletedRecords? (required)
deletedRecord: "transient"

#repositoryName: Repository name for Identify verb (required)
repositoryName: "SPK OAI Data Provider for MIMO"

#
##
### 5 RESUMPTION CHUNKING
##
#

#chunkSize (integer): No of results per chunk.
chunkSize: 100

#chunkCacheMaxSize (integer): Max no of chunk descriptions stored in request cache
# before old chunk descriptions are deleted. maxChunkCache must be greater than
# the max number of chunks per request.
chunkCacheMaxSize: 4000

#
##
### 6 SUPPORTED METADATA FORMATS
##
#

#example
# mpx:
#  ns_uri: "http://www.mpx.org/mpx"
#  ns_schema: "https://github.com/mokko/MPX/raw/master/latest/mpx.xsd"

GlobalFormats:
  mpx:
   ns_uri: "http://www.mpx.org/mpx"
   ns_schema: "https://github.com/mokko/MPX/raw/master/latest/mpx.xsd"
  lido:
   ns_uri: "http://www.lido-schema.org"
   ns_schema: "http://www.lido-schema.org/schema/v1.0/lido-v1.0.xsd"
  oai_dc:
   ns_uri: "http://www.openarchives.org/OAI/2.0/oai_dc/"
   ns_schema: "http://www.openarchives.org/OAI/2.0/oai_dc.xsd"
#  museumdat:
#   ns_uri: "http://museum.zib.de/museumdat/"
#   ns_schema: "http://museum.zib.de/museumdat/museumdat-v1.0.xsd"


#
##
### 7 SET LIBRARY
##
#

#example
#setSpec:
# setName: 'this is a setName'
# setDescription:
#  - <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:description>This set contains metadata describing electronic music recordings made during the 1950ies</dc:description></oai_dc:dc>

setLibrary:
  78:
   setName: 'Schellackplatten aus dem Phonogramm-Archiv (ursprünglich für DISMARC exportiert)'
  MIMO:
   setName: 'Musical Instruments selected for MIMO project'
  test:
   setName: 'testing setSpecs - might not work without this one'

#
##
### 8 SPECIFIC TO SQLite ENGINE
##
#

#dbfile (path): location of sqlite db
dbfile: "/home/Mengel/projects/Salsa_OAI2/data/db"
