##NEW CONFIG
#
##
###1. BASIC DANCER CONFIG
##
#

#layout: "main"
log: "debug"
logger: "console"
appname: "Salsa_OAI2"
content_type: "text/xml"

#
##
###2. FILES AND DIRS
##
#

xml_undigested: todo
#dir or file with large xml file containing multiple records
#is processed by script (todo)

xml_store: "/home/Mengel/projects/Salsa_OAI/index/fs"
#xml source directory where xml records lie (1 record per file)

headercache_YAML: "/home/Mengel/projects/Salsa_OAI/index/ListIdentifiers.yaml"
#headercache is a yaml file containing all information for the OAI headers
#is written by script (which?) and read by SALSA OAI


#
##
### 3 TRANSFORMATIONS
##
#


XSLT_dir: "/home/Mengel/projects/Salsa_OAI/xslt"
XSLT: '/oai2.xsl'


#
##
### 4 OAI IDENTIFY FOR THIS SERVER
##
#

oai_adminEmail: "mauricemengel@gmail.com"
oai_baseURL: "http://localhost:3000/oai"
oai_deletedRecord: "no"
#oai_deletedRecord: no, persistent, transient
oai_granularity: "YYYY-MM-DDThh:mm:ssZ"
oai_repositoryName: "agoodname"
oai_requestURL: "http://localhost:3000/oai?Identify"

#
##
### 5 SUPPORTED METADATA FORMATS
##
#

GlobalFormats:
  mpx:
   ns_uri: "http://www.mpx.org/mpx"
   ns_schema: "file:/c:/cygwin/home/Mengel/usr/levelup/lib/mpx-lvl2.v2.xsd"
  lido:
   ns_uri: "http://www.lido-schema.org"
   ns_schema: "http://www.lido-schema.org/schema/v0.9/lido-v0.9.xsd"
  oai_dc:
   ns_uri: "http://www.openarchives.org/OAI/2.0/oai_dc/"
   ns_schema: "http://www.openarchives.org/OAI/2.0/oai_dc.xsd"
#
##
### 6 SET LIBRARY
##
#
#this format allows only for one setDescription, but in fact there can be many
setLibrary:
  test:
   setName: "this is a longer name"
   setDescription:
    - <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:description>This set contains metadata describing electronic music recordings made during the 1950ies</dc:description></oai_dc:dc>
    - <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:description>This set contains metadata describing electronic music recordings made during the 1950ies</dc:description></oai_dc:dc>
  Maurice:
   setName: 'mamamama'
   setDescription:
    - <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:description>This set contains metadata describing electronic music recordings made during the 1950ies</dc:description></oai_dc:dc>
  Sydney:
   setName: "v"
  another_test:
   setName: "b"



