#
##
### 1 BASIC DANCER CONFIG AND OTHER SIMPLE STUFF
##
#

appname: "SalsaOAI"
content_type: "text/html"
debug: 'Salsa_OAI::salsa_debug'
warning: 'Salsa_OAI::salsa_debug'
XSLT_dir: '/home/maurice/projects/SalsaOAI/xslt'
xslt: '/oai2.xsl'

#
##
### 2 ENGINE
##
#

engine:
  engine: 'HTTP::OAI::DataProvider::Engine::SQLite'
  nativeFormat: 
    'mpx': 'http://www.mpx.org/mpx'
  locateXSL: 'Salsa_OAI::MPX::locateXSL'
  chunkCache:
  recordsPerChunk: 100
  maxChunks: 4000
  dbfile: "/home/maurice/projects/SalsaOAI/data/db"
  #extractRecords (callback): returns HTTP::OAI::Record from source xml
  extractRecords: 'Salsa_OAI::MPX::extractRecords'

#
##
### 4 OAI IDENTIFY FOR THIS SERVER
##
#

identify:
 adminEmail: 'mauricemengel@gmail.com'
 baseURL: 'http://localhost:3000/oai'
 deletedRecord: 'transient'
 repositoryName: "SPK OAI Data Provider for MIMO"

#
##
### 6 SUPPORTED METADATA FORMATS
##
#

#example
# mpx:
#  ns_uri: "http://www.mpx.org/mpx"
#  ns_schema: "https://github.com/mokko/MPX/raw/master/latest/mpx.xsd"

globalFormats:
  mpx:
   ns_uri: "http://www.mpx.org/mpx"
   ns_schema: "https://github.com/mokko/MPX/raw/master/latest/mpx.xsd"
  lido:
   ns_uri: "http://www.lido-schema.org"
   ns_schema: "http://www.lido-schema.org/schema/v1.0/lido-v1.0.xsd"
  oai_dc:
   ns_uri: "http://www.openarchives.org/OAI/2.0/oai_dc/"
   ns_schema: "http://www.openarchives.org/OAI/2.0/oai_dc.xsd"


#
##
### 7 SET LIBRARY
##
#

#example
#setSpec:
# setName: 'this is a setName'
# setDescription:
#  - <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:description>This set contains metadata describing electronic music recordings made during the 1950ies</dc:description></oai_dc:dc>

setLibrary:
  78:
   setName: 'Schellackplatten aus dem Phonogramm-Archiv (ursprünglich für DISMARC exportiert)'
  MIMO:
   setName: 'Musical Instruments selected for MIMO project'
  test:
   setName: 'testing setSpecs - might not work without this one'

