---
abstract: 'Simple OAI data provider'
author:
  - 'Maurice Mengel <mauricemengel@gmail.com>'
build_requires:
  Dancer::Test: 0
  English: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Salsa_OAI
requires:
  Carp: 0
  Cwd: 0
  DBD::SQLite: 0
  DBI: 0
  Dancer: 0
  Date::Manip: 0
  Encode: 0
  FindBin: 0
  Getopt::Std: 0
  HTTP::OAI: 0
  HTTP::OAI::DataProvider: 0
  HTTP::OAI::DataProvider::SQLite: 0
  HTTP::OAI::Metadata: 0
  HTTP::OAI::Repository: 0
  IO::File: 0
  LWP::Simple: 0
  Pod::Usage: 0
  SOAP::DateTime: 0
  Text::CSV: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  XML::LibXSLT: 0
  XML::Writer: 0
  utf8: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Salsa_OAI
  homepage: https://github.com/mokko/Salsa_OAI2/wiki
  repository: git://github.com/mokko/Salsa_OAI2.git
version: 0.014
